services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - '0.0.0.0:5432:5432'

  backend:
    build:
      context: ./criptoBack
      dockerfile: ./dockerfile
    container_name: backend
    command: sh -c "./start.sh"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build:
      context: ./criptofront
      dockerfile: ./dockerfile
    container_name: front
    ports:
      - "80:80"
    depends_on:
      - backend

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env
    depends_on:
      - db
      # - backend



