# Generated by Django 5.0.6 on 2024-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('item', models.TextField(blank=True, max_length=40, null=True)),
                ('deposit', models.TextField(blank=True, null=True)),
                ('borrow', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
